[versions]
agp = "7.4.2"
compose-jb = "1.3.1"
kotlin = "1.8.10"
spotless = "6.17.0"
ktlint = "0.48.2"
publish = "0.25.1"
markdown = "0.4.1"
napier = "2.6.1"
imageloader = "1.2.10"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
composeJb = { id = "org.jetbrains.compose", version.ref = "compose-jb" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }

[libraries]
markdown = { module = "org.jetbrains:markdown", version.ref = "markdown" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
imageloader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "imageloader" }
